export interface Novel {
  title: string;
  author: string;
  category: string;
}

export const novels: Novel[] = [
  { title: "Oroonoko", author: "Aphra Behn", category: "British" },
  { title: "Robinson Crusoe", author: "Daniel Defoe", category: "British" },
  { title: "Moll Flanders", author: "Daniel Defoe", category: "British" },
  { title: "Pamela", author: "Samuel Richardson", category: "British" },
  { title: "Clarissa", author: "Samuel Richardson", category: "British" },
  { title: "Tom Jones", author: "Henry Fielding", category: "British" },
  { title: "Joseph Andrews", author: "Henry Fielding", category: "British" },
  { title: "Tristram Shandy", author: "Laurence Sterne", category: "British" },
  { title: "Gulliver's Travels", author: "Jonathan Swift", category: "British" },
  { title: "Roderick Random", author: "Tobias Smollett", category: "British" },
  { title: "The Castle of Otranto", author: "Horace Walpole", category: "British" },
  { title: "The Mysteries of Udolpho", author: "Ann Radcliffe", category: "British" },
  { title: "The Vicar of Wakefield", author: "Oliver Goldsmith", category: "British" },
  { title: "Ivanhoe", author: "Walter Scott", category: "British" },
  { title: "Bride of Lammermoor", author: "Walter Scott", category: "British" },
  { title: "Kenilworth", author: "Walter Scott", category: "British" },
  { title: "Pride and Prejudice", author: "Jane Austen", category: "British" },
  { title: "Emma", author: "Jane Austen", category: "British" },
  { title: "Sense and Sensibility", author: "Jane Austen", category: "British" },
  { title: "Mansfield Park", author: "Jane Austen", category: "British" },
  { title: "Frankenstein", author: "Mary Shelley", category: "British" },
  { title: "Pickwick Papers", author: "Charles Dickens", category: "British" },
  { title: "Oliver Twist", author: "Charles Dickens", category: "British" },
  { title: "Nicholas Nickleby", author: "Charles Dickens", category: "British" },
  { title: "Bleak House", author: "Charles Dickens", category: "British" },
  { title: "David Copperfield", author: "Charles Dickens", category: "British" },
  { title: "A Tale of Two Cities", author: "Charles Dickens", category: "British" },
  { title: "Hard Times", author: "Charles Dickens", category: "British" },
  { title: "Great Expectations", author: "Charles Dickens", category: "British" },
  { title: "Little Dorrit", author: "Charles Dickens", category: "British" },
  { title: "Jane Eyre", author: "Charlotte Brontë", category: "British" },
  { title: "Wuthering Heights", author: "Emily Brontë", category: "British" },
  { title: "Daniel Deronda", author: "George Eliot", category: "British" },
  { title: "The Mill on the Floss", author: "George Eliot", category: "British" },
  { title: "Middlemarch", author: "George Eliot", category: "British" },
  { title: "Silas Marner", author: "George Eliot", category: "British" },
  { title: "The Return of the Native", author: "Thomas Hardy", category: "British" },
  { title: "Far from the Madding Crowd", author: "Thomas Hardy", category: "British" },
  { title: "The Mayor of Casterbridge", author: "Thomas Hardy", category: "British" },
  { title: "Tess of the d'Urbervilles", author: "Thomas Hardy", category: "British" },
  { title: "Jude the Obscure", author: "Thomas Hardy", category: "British" },
  { title: "The Moonstone", author: "Wilkie Collins", category: "British" },
  { title: "The Picture of Dorian Gray", author: "Oscar Wilde", category: "British" },
  { title: "Vanity Fair", author: "William Makepeace Thackeray", category: "British" },
  { title: "North and South", author: "Elizabeth Gaskell", category: "British" },
  { title: "The Time Machine", author: "H. G. Wells", category: "British" },
  { title: "The Invisible Man", author: "H. G. Wells", category: "British" },
  { title: "Kim", author: "Rudyard Kipling", category: "British" },
  { title: "Heart of Darkness", author: "Joseph Conrad", category: "British" },
  { title: "Lord Jim", author: "Joseph Conrad", category: "British" },
  { title: "Nostromo", author: "Joseph Conrad", category: "British" },
  { title: "A Passage to India", author: "E. M. Forster", category: "British" },
  { title: "Howards End", author: "E. M. Forster", category: "British" },
  { title: "A Room with a View", author: "E. M. Forster", category: "British" },
  { title: "Where Angels Fear to Tread", author: "E. M. Forster", category: "British" },
  { title: "The Longest Journey", author: "E. M. Forster", category: "British" },
  { title: "Sons and Lovers", author: "D. H. Lawrence", category: "British" },
  { title: "The Rainbow", author: "D. H. Lawrence", category: "British" },
  { title: "Women in Love", author: "D. H. Lawrence", category: "British" },
  { title: "Lady Chatterley's Lover", author: "D. H. Lawrence", category: "British" },
  { title: "A Portrait of the Artist as a Young Man", author: "James Joyce", category: "British" },
  { title: "Ulysses", author: "James Joyce", category: "British" },
  { title: "Mrs Dalloway", author: "Virginia Woolf", category: "British" },
  { title: "To the Lighthouse", author: "Virginia Woolf", category: "British" },
  { title: "Orlando", author: "Virginia Woolf", category: "British" },
  { title: "The Waves", author: "Virginia Woolf", category: "British" },
  { title: "Brave New World", author: "Aldous Huxley", category: "British" },
  { title: "Decline and Fall", author: "Evelyn Waugh", category: "British" },
  { title: "A Handful of Dust", author: "Evelyn Waugh", category: "British" },
  { title: "1984", author: "George Orwell", category: "British" },
  { title: "Animal Farm", author: "George Orwell", category: "British" },
  { title: "Lucky Jim", author: "Kingsley Amis", category: "British" },
  { title: "Changing Places", author: "David Lodge", category: "British" },
  { title: "Hurry on Down", author: "John Wain", category: "British" },
  { title: "Room at the Top", author: "John Braine", category: "British" },
  { title: "Life at the Top", author: "John Braine", category: "British" },
  { title: "Under the Net", author: "Iris Murdoch", category: "British" },
  { title: "The Sea, the Sea", author: "Iris Murdoch", category: "British" },
  { title: "The Prime of Miss Jean Brodie", author: "Muriel Spark", category: "British" },
  { title: "Possession", author: "A. S. Byatt", category: "British" },
  { title: "The Golden Notebook", author: "Doris Lessing", category: "British" },
  { title: "Saturday Night and Sunday Morning", author: "Alan Sillitoe", category: "British" },
  { title: "Hemlock and After", author: "Angus Wilson", category: "British" },
  { title: "The French Lieutenant's Woman", author: "John Fowles", category: "British" },
  { title: "Lord of the Flies", author: "William Golding", category: "British" },
  { title: "The Power and the Glory", author: "Graham Greene", category: "British" },
  { title: "A Clockwork Orange", author: "Anthony Burgess", category: "British" },
  { title: "Atonement", author: "Ian McEwan", category: "British" },
  { title: "The Sense of an Ending", author: "Julian Barnes", category: "British" },
  { title: "The Remains of the Day", author: "Kazuo Ishiguro", category: "British" },
  { title: "Never Let Me Go", author: "Kazuo Ishiguro", category: "British" },
  { title: "Rajmohan's Wife", author: "Bankim Chandra Chattopadhyay", category: "Indian" },
  { title: "Swami and Friends", author: "R. K. Narayan", category: "Indian" },
  { title: "The Bachelor of Arts", author: "R. K. Narayan", category: "Indian" },
  { title: "The English Teacher", author: "R. K. Narayan", category: "Indian" },
  { title: "The Guide", author: "R. K. Narayan", category: "Indian" },
  { title: "Waiting for the Mahatma", author: "R. K. Narayan", category: "Indian" },
  { title: "The Man-Eater of Malgudi", author: "R. K. Narayan", category: "Indian" },
  { title: "Untouchable", author: "Mulk Raj Anand", category: "Indian" },
  { title: "Coolie", author: "Mulk Raj Anand", category: "Indian" },
  { title: "Two Leaves and a Bud", author: "Mulk Raj Anand", category: "Indian" },
  { title: "The Village", author: "Mulk Raj Anand", category: "Indian" },
  { title: "Across the Black Waters", author: "Mulk Raj Anand", category: "Indian" },
  { title: "Kanthapura", author: "Raja Rao", category: "Indian" },
  { title: "The Serpent and the Rope", author: "Raja Rao", category: "Indian" },
  { title: "Cry, the Peacock", author: "Anita Desai", category: "Indian" },
  { title: "Clear Light of Day", author: "Anita Desai", category: "Indian" },
  { title: "In Custody", author: "Anita Desai", category: "Indian" },
  { title: "Fire on the Mountain", author: "Anita Desai", category: "Indian" },
  { title: "Nectar in a Sieve", author: "Kamala Markandaya", category: "Indian" },
  { title: "Midnight's Children", author: "Salman Rushdie", category: "Indian" },
  { title: "Shame", author: "Salman Rushdie", category: "Indian" },
  { title: "The Satanic Verses", author: "Salman Rushdie", category: "Indian" },
  { title: "The Moor's Last Sigh", author: "Salman Rushdie", category: "Indian" },
  { title: "The God of Small Things", author: "Arundhati Roy", category: "Indian" },
  { title: "The Ministry of Utmost Happiness", author: "Arundhati Roy", category: "Indian" },
  { title: "The Shadow Lines", author: "Amitav Ghosh", category: "Indian" },
  { title: "The Glass Palace", author: "Amitav Ghosh", category: "Indian" },
  { title: "The Hungry Tide", author: "Amitav Ghosh", category: "Indian" },
  { title: "The Calcutta Chromosome", author: "Amitav Ghosh", category: "Indian" },
  { title: "Sea of Poppies", author: "Amitav Ghosh", category: "Indian" },
  { title: "River of Smoke", author: "Amitav Ghosh", category: "Indian" },
  { title: "A Suitable Boy", author: "Vikram Seth", category: "Indian" },
  { title: "An Equal Music", author: "Vikram Seth", category: "Indian" },
  { title: "Red Earth and Pouring Rain", author: "Vikram Chandra", category: "Indian" },
  { title: "Sacred Games", author: "Vikram Chandra", category: "Indian" },
  { title: "Train to Pakistan", author: "Khushwant Singh", category: "Indian" },
  { title: "Delhi: A Novel", author: "Khushwant Singh", category: "Indian" },
  { title: "So Many Hungers", author: "Bhabani Bhattacharya", category: "Indian" },
  { title: "That Long Silence", author: "Shashi Deshpande", category: "Indian" },
  { title: "A Bend in the Ganges", author: "Manohar Malgonkar", category: "Indian" },
  { title: "Such a Long Journey", author: "Rohinton Mistry", category: "Indian" },
  { title: "A Fine Balance", author: "Rohinton Mistry", category: "Indian" },
  { title: "The Namesake", author: "Jhumpa Lahiri", category: "Indian" },
  { title: "The Inheritance of Loss", author: "Kiran Desai", category: "Indian" },
  { title: "Rich Like Us", author: "Nayantara Sahgal", category: "Indian" },
  { title: "Storm in Chandigarh", author: "Nayantara Sahgal", category: "Indian" },
  { title: "Sunlight on a Broken Column", author: "Attia Hosain", category: "Indian" },
  { title: "Azadi", author: "Chaman Nahal", category: "Indian" },
  { title: "The Strange Case of Billy Biswas", author: "Arun Joshi", category: "Indian" },
  { title: "Jasmine", author: "Bharati Mukherjee", category: "Indian" },
  { title: "Desirable Daughters", author: "Bharati Mukherjee", category: "Indian" },
  { title: "Nampally Road", author: "Meena Alexander", category: "Indian" },
  { title: "Feminist Fables", author: "Suniti Namjoshi", category: "Indian" },
  { title: "All About H. Hatterr", author: "G. V. Desani", category: "Indian" },
  { title: "English, August", author: "Upamanyu Chatterjee", category: "Indian" },
  { title: "The Trotter-Nama", author: "Allan Sealy", category: "Indian" },
  { title: "The White Tiger", author: "Aravind Adiga", category: "Indian" },
  { title: "Turbulence", author: "Samit Basu", category: "Indian" },
  { title: "Escape", author: "Manjula Padmanabhan", category: "Indian" },
  { title: "The Palace of Illusions", author: "Chitra Banerjee Divakaruni", category: "Indian" },
  { title: "The Forest of Enchantments", author: "Chitra Banerjee Divakaruni", category: "Indian" },
  { title: "The Immortals of Meluha", author: "Amish Tripathi", category: "Indian" },
  { title: "Ice-Candy-Man", author: "Bapsi Sidhwa", category: "Indian" },
  { title: "Tomb of Sand", author: "Geetanjali Shree", category: "Indian" },
  { title: "The Return of Vaman", author: "Jayant Naralikar", category: "Indian" },
  { title: "Sita: An Illustrated Retelling of Ramayana", author: "Devdutt Pattanaik", category: "Indian" },
  { title: "Rise of Shivagami", author: "Anand Neelakantan", category: "Indian" },
  { title: "Difficult Daughters", author: "Manju Kapur", category: "Indian" },
  { title: "The Scarlet Letter", author: "Nathaniel Hawthorne", category: "American" },
  { title: "Moby-Dick", author: "Herman Melville", category: "American" },
  { title: "The Last of the Mohicans", author: "James Fenimore Cooper", category: "American" },
  { title: "Uncle Tom's Cabin", author: "Harriet Beecher Stowe", category: "American" },
  { title: "Adventures of Huckleberry Finn", author: "Mark Twain", category: "American" },
  { title: "The Portrait of a Lady", author: "Henry James", category: "American" },
  { title: "The Red Badge of Courage", author: "Stephen Crane", category: "American" },
  { title: "The Awakening", author: "Kate Chopin", category: "American" },
  { title: "The Great Gatsby", author: "F. Scott Fitzgerald", category: "American" },
  { title: "The Old Man and the Sea", author: "Ernest Hemingway", category: "American" },
  { title: "The Sun Also Rises", author: "Ernest Hemingway", category: "American" },
  { title: "A Farewell to Arms", author: "Ernest Hemingway", category: "American" },
  { title: "For Whom the Bell Tolls", author: "Ernest Hemingway", category: "American" },
  { title: "The Sound and the Fury", author: "William Faulkner", category: "American" },
  { title: "The Grapes of Wrath", author: "John Steinbeck", category: "American" },
  { title: "Their Eyes Were Watching God", author: "Zora Neale Hurston", category: "American" },
  { title: "Native Son", author: "Richard Wright", category: "American" },
  { title: "The Catcher in the Rye", author: "J. D. Salinger", category: "American" },
  { title: "Invisible Man", author: "Ralph Ellison", category: "American" },
  { title: "On the Road", author: "Jack Kerouac", category: "American" },
  { title: "Catch-22", author: "Joseph Heller", category: "American" },
  { title: "Gravity's Rainbow", author: "Thomas Pynchon", category: "American" },
  { title: "Slaughterhouse-Five", author: "Kurt Vonnegut", category: "American" },
  { title: "White Noise", author: "Don DeLillo", category: "American" },
  { title: "Beloved", author: "Toni Morrison", category: "American" },
  { title: "Sula", author: "Toni Morrison", category: "American" },
  { title: "Song of Solomon", author: "Toni Morrison", category: "American" },
  { title: "The Bluest Eye", author: "Toni Morrison", category: "American" },
  { title: "The Color Purple", author: "Alice Walker", category: "American" },
  { title: "The Joy Luck Club", author: "Amy Tan", category: "American" },
  { title: "American Pastoral", author: "Philip Roth", category: "American" },
  { title: "The Age of Innocence", author: "Edith Wharton", category: "American" },
  { title: "Herzog", author: "Saul Bellow", category: "American" },
  { title: "Go Tell It on the Mountain", author: "James Baldwin", category: "American" },
  { title: "Little Women", author: "Louisa May Alcott", category: "American" },
  { title: "The Song of Achilles", author: "Madeline Miller", category: "American" },
  { title: "Middlesex", author: "Jeffrey Eugenides", category: "American" },
  { title: "Buddenbrooks", author: "Thomas Mann", category: "World" },
  { title: "The Magic Mountain", author: "Thomas Mann", category: "World" },
  { title: "Things Fall Apart", author: "Chinua Achebe", category: "World" },
  { title: "Arrow of God", author: "Chinua Achebe", category: "World" },
  { title: "A Grain of Wheat", author: "Ngũgĩ wa Thiong'o", category: "World" },
  { title: "Petals of Blood", author: "Ngũgĩ wa Thiong'o", category: "World" },
  { title: "The River Between", author: "Ngũgĩ wa Thiong'o", category: "World" },
  { title: "The Interpreters", author: "Wole Soyinka", category: "World" },
  { title: "Disgrace", author: "J. M. Coetzee", category: "World" },
  { title: "Waiting for the Barbarians", author: "J. M. Coetzee", category: "World" },
  { title: "Life and Times of Michael K", author: "J. M. Coetzee", category: "World" },
  { title: "July's People", author: "Nadine Gordimer", category: "World" },
  { title: "Son's Story", author: "Nadine Gordimer", category: "World" },
  { title: "Wide Sargasso Sea", author: "Jean Rhys", category: "World" },
  { title: "A House for Mr Biswas", author: "V. S. Naipaul", category: "World" },
  { title: "The Mimic Men", author: "V. S. Naipaul", category: "World" },
  { title: "Annie John", author: "Jamaica Kincaid", category: "World" },
  { title: "Lucy", author: "Jamaica Kincaid", category: "World" },
  { title: "Voss", author: "Patrick White", category: "World" },
  { title: "The Tree of Man", author: "Patrick White", category: "World" },
  { title: "Oscar and Lucinda", author: "Peter Carey", category: "World" },
  { title: "True History of the Kelly Gang", author: "Peter Carey", category: "World" },
  { title: "Remembering Babylon", author: "David Malouf", category: "World" },
  { title: "The Book Thief", author: "Markus Zusak", category: "World" },
  { title: "Surfacing", author: "Margaret Atwood", category: "World" },
  { title: "The Edible Woman", author: "Margaret Atwood", category: "World" },
  { title: "The Handmaid's Tale", author: "Margaret Atwood", category: "World" },
  { title: "Cat's Eye", author: "Margaret Atwood", category: "World" },
  { title: "The Blind Assassin", author: "Margaret Atwood", category: "World" },
  { title: "The Testaments", author: "Margaret Atwood", category: "World" },
  { title: "The Stone Angel", author: "Margaret Laurence", category: "World" },
  { title: "The Diviners", author: "Margaret Laurence", category: "World" },
  { title: "The English Patient", author: "Michael Ondaatje", category: "World" },
  { title: "Life of Pi", author: "Yann Martel", category: "World" },
  { title: "Madame Bovary", author: "Gustave Flaubert", category: "World" },
  { title: "The Stranger", author: "Albert Camus", category: "World" },
  { title: "The Plague", author: "Albert Camus", category: "World" },
  { title: "Les Miserables", author: "Victor Hugo", category: "World" },
  { title: "The Age of Reason", author: "Jean-Paul Sartre", category: "World" },
  { title: "The Trial", author: "Franz Kafka", category: "World" },
  { title: "The Castle", author: "Franz Kafka", category: "World" },
  { title: "The Metamorphosis", author: "Franz Kafka", category: "World" },
  { title: "The Tin Drum", author: "Gunter Grass", category: "World" },
  { title: "The Name of the Rose", author: "Umberto Eco", category: "World" },
  { title: "If Not Now, When?", author: "Primo Levi", category: "World" },
  { title: "Don Quixote", author: "Miguel de Cervantes", category: "World" },
  { title: "Blindness", author: "Jose Saramago", category: "World" },
  { title: "The Gospel According to Jesus Christ", author: "Jose Saramago", category: "World" },
  { title: "War and Peace", author: "Leo Tolstoy", category: "World" },
  { title: "Anna Karenina", author: "Leo Tolstoy", category: "World" },
  { title: "Crime and Punishment", author: "Fyodor Dostoevsky", category: "World" },
  { title: "The Brothers Karamazov", author: "Fyodor Dostoevsky", category: "World" },
  { title: "The Master and Margarita", author: "Mikhail Bulgakov", category: "World" },
  { title: "Fathers and Sons", author: "Ivan Turgenev", category: "World" },
  { title: "One Hundred Years of Solitude", author: "Gabriel Garcia Marquez", category: "World" },
  { title: "Love in the Time of Cholera", author: "Gabriel Garcia Marquez", category: "World" },
  { title: "The Time of the Hero", author: "Mario Vargas Llosa", category: "World" },
  { title: "The House of the Spirits", author: "Isabel Allende", category: "World" },
  { title: "Palace Walk", author: "Naguib Mahfouz", category: "World" },
  { title: "My Name is Red", author: "Orhan Pamuk", category: "World" },
  { title: "Snow", author: "Orhan Pamuk", category: "World" },
  { title: "Kafka on the Shore", author: "Haruki Murakami", category: "World" },
  { title: "Norwegian Wood", author: "Haruki Murakami", category: "World" },
  { title: "Snow Country", author: "Yasunari Kawabata", category: "World" },
  { title: "Red Sorghum", author: "Mo Yan", category: "World" },
  { title: "The Bone People", author: "Keri Hulme", category: "World" },
  { title: "The Luminaries", author: "Eleanor Catton", category: "World" },
  { title: "Paradise", author: "Abdulrazak Gurnah", category: "World" },
  { title: "By the Sea", author: "Abdulrazak Gurnah", category: "World" },
  { title: "Satantango", author: "Laszlo Krasznahorkai", category: "World" },
  { title: "The Vegetarian", author: "Han Kang", category: "World" },
  { title: "Flesh", author: "David Szalay", category: "World" },
  { title: "The Seven Moons of Maali Almeida", author: "Shehan Karunatilaka", category: "World" },
  { title: "Shuggie Bain", author: "Douglas Stuart", category: "World" },
  { title: "The Promise", author: "Damon Galgut", category: "World" },
  { title: "Reading Lolita in Tehran", author: "Azar Nafisi", category: "World" },
  { title: "Salt", author: "Earl Lovelace", category: "World" },
  { title: "Purple Hibiscus", author: "Chimamanda Ngozi Adichie", category: "World" },
  { title: "Funny Boy", author: "Shyam Selvadurai", category: "World" },
  { title: "Nana", author: "Emile Zola", category: "World" },
  { title: "Persepolis 2", author: "Marjane Satrapi", category: "World" },
  { title: "Lolita", author: "Vladimir Nabokov", category: "World" },
  { title: "The Bride", author: "Bapsi Sidhwa", category: "World" },
  { title: "Burnt Shadows", author: "Kamila Shamsie", category: "World" },
  { title: "Home Fire", author: "Kamila Shamsie", category: "World" },
  { title: "The Reluctant Fundamentalist", author: "Mohsin Hamid", category: "World" },
  { title: "The Kite Runner", author: "Khaled Hosseini", category: "World" },
  { title: "A Thousand Splendid Suns", author: "Khaled Hosseini", category: "World" }
];
