export interface Drama {
  title: string;
  author: string;
  category: string;
}

export const dramas: Drama[] = [
  // British Plays
  { title: "Ralf Roister Doister", author: "Thomas Norton", category: "British" },
  { title: "Gorboduct", author: "Thomas Sackville", category: "British" },
  { title: "Grammer Gutons Neelde", author: "Anonymous", category: "British" },
  { title: "The Four PP", author: "John Heywood", category: "British" },
  { title: "The Play of the Weather", author: "John Heywood", category: "British" },
  { title: "Dr. Fuastus", author: "Christopher Marlow", category: "British" },
  { title: "Tamburlaine", author: "Christopher Marlow", category: "British" },
  { title: "Jew of Malta", author: "Christopher Marlow", category: "British" },
  { title: "Edward II", author: "Christopher Marlow", category: "British" },
  { title: "The Spanish Tragedy", author: "Thomas Kyd", category: "British" },
  { title: "Hamlet", author: "Shakespeare", category: "British" },
  { title: "Othello", author: "Shakespeare", category: "British" },
  { title: "Macbeth", author: "Shakespeare", category: "British" },
  { title: "King Lear", author: "Shakespeare", category: "British" },
  { title: "Much Ado About Nothing", author: "Shakespeare", category: "British" },
  { title: "As you like it", author: "Shakespeare", category: "British" },
  { title: "Henry series all plays", author: "Shakespeare", category: "British" },
  { title: "Richard II", author: "Shakespeare", category: "British" },
  { title: "Julius Caesar", author: "Shakespeare", category: "British" },
  { title: "Romeo and Juliet", author: "Shakespeare", category: "British" },
  { title: "Titus Andronicus", author: "Shakespeare", category: "British" },
  { title: "Loves Labour Lost", author: "Shakespeare", category: "British" },
  { title: "Midsummer Nights Dream", author: "Shakespeare", category: "British" },
  { title: "All’s Well that End’s Well", author: "Shakespeare", category: "British" },
  { title: "Two Gentlemen of Verona", author: "Shakespeare", category: "British" },
  { title: "Measure for Measure", author: "Shakespeare", category: "British" },
  { title: "Merchant of Venice", author: "Shakespeare", category: "British" },
  { title: "Twelfth Night", author: "Shakespeare", category: "British" },
  { title: "Antony and Cleopatra", author: "Shakespeare", category: "British" },
  { title: "Tempest", author: "Shakespeare", category: "British" },
  { title: "Comedy of Error", author: "Shakespeare", category: "British" },
  { title: "Every Man in his Humour", author: "Ben Jonson", category: "British" },
  { title: "Every Man out of His Humour", author: "Ben Jonson", category: "British" },
  { title: "The Alchemist", author: "Ben Jonson", category: "British" },
  { title: "Volpone the fox", author: "Ben Jonson", category: "British" },
  { title: "Epicoene, Silent woman", author: "Ben Jonson", category: "British" },
  { title: "The Knight of the Burning Pestle", author: "Beaumont", category: "British" },
  { title: "The Maid’s Tragedy", author: "Beaumont and Fletcher", category: "British" },
  { title: "The Changeling", author: "Thomas Middleton", category: "British" },
  { title: "A Game at Chess", author: "Thomas Middleton", category: "British" },
  { title: "Women Beware Women", author: "Thomas Middleton", category: "British" },
  { title: "The White Devil", author: "John Webster", category: "British" },
  { title: "The Duchess of Malfi", author: "John Webster", category: "British" },
  { title: "Tis Pity She’s a Whore", author: "John Ford", category: "British" },
  { title: "The Shoemaker's Holiday", author: "Thomas Dekker", category: "British" },
  { title: "Samson Agonistes", author: "John Milton", category: "British" },
  { title: "All for Love", author: "John Dryden", category: "British" },
  { title: "Conquest of Granda", author: "John Dryden", category: "British" },
  { title: "The Country Wife", author: "William Wycherley", category: "British" },
  { title: "Love in a Wood", author: "William Wycherley", category: "British" },
  { title: "The Plain Dealer", author: "William Wycherley", category: "British" },
  { title: "The Relapse", author: "John Vanbrugh", category: "British" },
  { title: "The Provoked Wife", author: "John Vanbrugh", category: "British" },
  { title: "The Man of Mode", author: "George Etheredge", category: "British" },
  { title: "The Comical Revenge", author: "George Etheredge", category: "British" },
  { title: "If She Would If Could", author: "George Etheredge", category: "British" },
  { title: "The Old Bachelor", author: "William Congreve", category: "British" },
  { title: "The Double Dealer", author: "William Congreve", category: "British" },
  { title: "Love for Love", author: "William Congreve", category: "British" },
  { title: "The Way of the World", author: "William Congreve", category: "British" },
  { title: "The Beggar’s Opera", author: "John Gay", category: "British" },
  { title: "She Stoops to Conquer", author: "Oliver Goldsmith", category: "British" },
  { title: "The Rival", author: "R. B. Sheridan", category: "British" },
  { title: "The School for Scandal", author: "R. B. Sheridan", category: "British" },
  { title: "The Critic", author: "R. B. Sheridan", category: "British" },
  { title: "A Woman of No Importance", author: "Oscar Wilde", category: "British" },
  { title: "The Importance of Being Earnest", author: "Oscar Wilde", category: "British" },
  { title: "An Ideal Husband", author: "Oscar Wilde", category: "British" },
  { title: "Silver Box", author: "John Galsworthy", category: "British" },
  { title: "Justice", author: "John Galsworthy", category: "British" },
  { title: "Strife", author: "John Galsworthy", category: "British" },
  { title: "Lady's not for Burning", author: "Christopher Fry", category: "British" },
  { title: "Pygmalion", author: "G. B. Shaw", category: "British" },
  { title: "Man and Superman", author: "G. B. Shaw", category: "British" },
  { title: "Widower's House", author: "G. B. Shaw", category: "British" },
  { title: "Candida", author: "G. B. Shaw", category: "British" },
  { title: "Heartbreak House", author: "G. B. Shaw", category: "British" },
  { title: "Saint Joan", author: "G. B. Shaw", category: "British" },
  { title: "Mrs. Warren's Profession", author: "G. B. Shaw", category: "British" },
  { title: "Major Barbara", author: "G. B. Shaw", category: "British" },
  { title: "Arms and Man", author: "G. B. Shaw", category: "British" },
  { title: "Doctor's Dilemma", author: "G. B. Shaw", category: "British" },
  { title: "Riders to the Sea", author: "J. M. Synge", category: "British" },
  { title: "The Play Boy of Western World", author: "J. M. Synge", category: "British" },
  { title: "Countess Cathleen", author: "W. Yeats", category: "British" },
  { title: "Juno and the Peacock", author: "Sean O’Cascy", category: "British" },
  { title: "The Plough and the Star", author: "Sean O’Cascy", category: "British" },
  { title: "The Shadow of a Gun Man", author: "Sean O’Cascy", category: "British" },
  { title: "Silver Tassie", author: "Sean O’Cascy", category: "British" },
  { title: "Murder in the Cathedral", author: "T. S. Eliot", category: "British" },
  { title: "Family Reunion", author: "T. S. Eliot", category: "British" },
  { title: "Confidential Clerk", author: "T. S. Eliot", category: "British" },
  { title: "The Cocktail Party", author: "T. S. Eliot", category: "British" },
  { title: "Waiting for Godot", author: "Samuel Bucket", category: "British" },
  { title: "Endgame", author: "Samuel Bucket", category: "British" },
  { title: "Krapp's Last Tape", author: "Samuel Bucket", category: "British" },
  { title: "Breath", author: "Samuel Bucket", category: "British" },
  { title: "Happy Days", author: "Harold Pinter", category: "British" },
  { title: "The Caretaker", author: "Harold Pinter", category: "British" },
  { title: "Home coming", author: "Harold Pinter", category: "British" },
  { title: "Birthday Party", author: "Harold Pinter", category: "British" },
  { title: "No Man's Land", author: "Harold Pinter", category: "British" },
  { title: "The Dumb Waiter", author: "Harold Pinter", category: "British" },
  { title: "Look Back in Anger", author: "John Osborn", category: "British" },
  { title: "The Entertainer", author: "John Osborn", category: "British" },
  { title: "Loot", author: "Joe Orton", category: "British" },
  { title: "Entertaining Mr Sloane", author: "Joe Orton", category: "British" },
  { title: "What a Butler Saw", author: "Joe Orton", category: "British" },
  { title: "Real Inspector's Hound", author: "Tom Stoppard", category: "British" },
  { title: "Rosencrantz and Guildenstern are Dead", author: "Tom Stoppard", category: "British" },
  { title: "Jumpers", author: "Tom Stoppard", category: "British" },
  { title: "Saved", author: "Edward Bond", category: "British" },
  { title: "Bundle", author: "Edward Bond", category: "British" },
  { title: "Lear", author: "Edward Bond", category: "British" },
  { title: "Bingo", author: "Edward Bond", category: "British" },
  { title: "Top Girls", author: "Caryl Churchill", category: "British" },
  { title: "Cloud Nine", author: "Caryl Churchill", category: "British" },

  // American Plays
  { title: "Emperor Jones", author: "Eugene O'Neil", category: "American" },
  { title: "Desire Under the Elms", author: "Eugene O'Neil", category: "American" },
  { title: "Hairy Ape", author: "Eugene O'Neil", category: "American" },
  { title: "Mourning Becomes Electra", author: "Eugene O'Neil", category: "American" },
  { title: "Long Day's Journey into Night", author: "Eugene O'Neil", category: "American" },
  { title: "The Iceman Cometh", author: "Eugene O'Neil", category: "American" },
  { title: "Strange Interlude", author: "Eugene O'Neil", category: "American" },
  { title: "A Cate on Hot Tin Roof", author: "Tennessee Williams", category: "American" },
  { title: "A Street Car Named Desire", author: "Tennessee Williams", category: "American" },
  { title: "The Glass Menageries", author: "Tennessee Williams", category: "American" },
  { title: "All My Sons", author: "Arther Miller", category: "American" },
  { title: "Death of A Salesman", author: "Arther Miller", category: "American" },
  { title: "The Crucible", author: "Arther Miller", category: "American" },
  { title: "The Zoo Story", author: "Edward Albee", category: "American" },
  { title: "An American Dream", author: "Edward Albee", category: "American" },
  { title: "Who's Afraid of Verginia Woolf", author: "Edward Albee", category: "American" },
  { title: "A Delicate Balance", author: "Edward Albee", category: "American" },

  // Indian Plays
  { title: "Abhijnanasakuntalam", author: "Kalidasa", category: "Indian" },
  { title: "Malavikagnimitram", author: "Kalidasa", category: "Indian" },
  { title: "Svapnavasavadatta", author: "Bhasa", category: "Indian" },
  { title: "Mrichchhakatika (The Little Clay Cart)", author: "Sudraka", category: "Indian" },
  { title: "Uttararamacharita", author: "Bhavabhuti", category: "Indian" },
  { title: "Mudrarakshasa", author: "Vishakhadatta", category: "Indian" },
  { title: "The Post Office (1912)", author: "Rabindranath Tagore", category: "Indian" },
  { title: "Chitra", author: "Rabindranath Tagore", category: "Indian" },
  { title: "The Dumb Dancer", author: "Asif Currimbhoy", category: "Indian" },
  { title: "Tughlaq", author: "Girish Karnad", category: "Indian" },
  { title: "Hayavadana", author: "Girish Karnad", category: "Indian" },
  { title: "Nagamandala", author: "Girish Karnad", category: "Indian" },
  { title: "The Fire and the Rain", author: "Girish Karnad", category: "Indian" },
  { title: "Ghashiram Kotwal", author: "Vijay Tendulkar", category: "Indian" },
  { title: "Sakharam Binder", author: "Vijay Tendulkar", category: "Indian" },
  { title: "Kamala", author: "Vijay Tendulkar", category: "Indian" },
  { title: "Silence! The Court is in Session", author: "Vijay Tendulkar", category: "Indian" },
  { title: "Vultures", author: "Vijay Tendulkar", category: "Indian" },
  { title: "Friends Story", author: "Vijay Tendulkar", category: "Indian" },
  { title: "Evam Indrajit", author: "Badal Sircar", category: "Indian" },
  { title: "Pagla Ghoda", author: "Badal Sircar", category: "Indian" },
  { title: "Final Solutions", author: "Mahesh Dattani", category: "Indian" },
  { title: "Tara", author: "Mahesh Dattani", category: "Indian" },
  { title: "Dance Like a Man", author: "Mahesh Dattani", category: "Indian" },
  { title: "Bravely Fought the Queen", author: "Mahesh Dattani", category: "Indian" },
  { title: "On a Muggy Night in Mumbai", author: "Mahesh Dattani", category: "Indian" },
  { title: "Seven Steps Around the Fire", author: "Mahesh Dattani", category: "Indian" },
  { title: "Harvest", author: "Manjula Padmanabhan", category: "Indian" },
  { title: "Lights Out", author: "Manjula Padmanabhan", category: "Indian" },
  { title: "The Other Side", author: "Manjula Padmanabhan", category: "Indian" },
  { title: "Larins Sahib", author: "Gurucharan Das", category: "Indian" },
  { title: "Ashadh Ka Ek Din", author: "Mohan Rakesh", category: "Indian" },
  { title: "Andha Yug", author: "Dharamvir Bharati", category: "Indian" },
  { title: "Mangalam", author: "Polly (Poli) Sengupta", category: "Indian" },
  { title: "Inner Spaces", author: "Polly (Poli) Sengupta", category: "Indian" },

  // Other Plays
  { title: "Oedipus Rex", author: "Sophocles", category: "Other" },
  { title: "Antigone", author: "Sophocles", category: "Other" },
  { title: "Medea", author: "Euripides", category: "Other" },
  { title: "Lysistrata", author: "Aristophanes", category: "Other" },
  { title: "The Frogs", author: "Aristophanes", category: "Other" },
  { title: "The Clouds", author: "Aristophanes", category: "Other" },
  { title: "Agamemnon", author: "Aeschylus", category: "Other" },
  { title: "Prometheus Bound", author: "Aeschylus", category: "Other" },
  { title: "The Misanthrope", author: "Molière", category: "Other" },
  { title: "Phaedra", author: "Jean Racine", category: "Other" },
  { title: "Huis Clos (No Exit)", author: "Jean-Paul Sartre", category: "Other" },
  { title: "Faust", author: "Johann Wolfgang von Goethe", category: "Other" },
  { title: "Mother Courage and Her Children", author: "Bertolt Brecht", category: "Other" },
  { title: "The Caucasian", author: "Bertolt Brecht", category: "Other" },
  { title: "Chalk Circle", author: "Bertolt Brecht", category: "Other" },
  { title: "Life of Galileo", author: "Bertolt Brecht", category: "Other" },
  { title: "A Doll’s House", author: "Henrik Ibsen", category: "Other" },
  { title: "Ghosts", author: "Henrik Ibsen", category: "Other" },
  { title: "The Cherry Orchard", author: "Anton Chekhov", category: "Other" },
  { title: "Three Sisters", author: "Anton Chekhov", category: "Other" },
  { title: "Six Characters in Search of an Author", author: "Luigi Pirandello", category: "Other" },
  { title: "Death and the King’s Horseman", author: "Wole Soyinka", category: "Other" },
  { title: "The Lion and the Jewel", author: "Wole Soyinka", category: "Other" }
];
